name: Build and Deploy on GitHub Pages
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node ☑
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      
      - name: Setup Yarn ☑
        uses: mskelton/setup-yarn@v3

      - name: Install JS dependencies and Build 🔧
        run: |
          yarn install
          yarn build

      - name: Deploy on messiasdias.github.io 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: github-pages
          publish_dir: ./dist
